"""Shared deterministic TCP/HTTP builders for synthetic rule suites.

Every value that influences the generated bytes is fixed: addresses, ports,
initial sequence numbers, timestamps, and header ordering.  Regenerating a case
with the same specification must produce a byte-identical PCAP.
"""

from __future__ import annotations

from pathlib import Path
from typing import Mapping

from scapy.all import IP, TCP, Raw, wrpcap


CLIENT_IP = "198.51.100.10"
SERVER_IP = "10.0.0.2"
CLIENT_PORT = 49152
CLIENT_ISN = 100
SERVER_ISN = 200
BASE_TIMESTAMP = 1_700_100_000
DEFAULT_HOST = "target.local"

_TRANSPORT_KEYS = frozenset(
    {"port", "direction", "client_ip", "server_ip", "raw_payload"}
)


def http_request(
    method: str,
    target: str,
    *,
    headers: Mapping[str, str] | None = None,
    body: str = "",
    version: str = "HTTP/1.1",
) -> bytes:
    """Build one deterministic HTTP request with a stable header order."""
    ordered: dict[str, str] = {"Host": DEFAULT_HOST, **dict(headers or {})}
    if body:
        ordered.setdefault("Content-Type", "application/x-www-form-urlencoded")
        ordered["Content-Length"] = str(len(body.encode()))
    head = f"{method} {target} {version}\r\n" + "".join(
        f"{key}: {value}\r\n" for key, value in ordered.items()
    )
    return (head + "\r\n" + body).encode()


def http_response(
    body: str,
    *,
    status: str = "200 OK",
    headers: Mapping[str, str] | None = None,
    version: str = "HTTP/1.1",
) -> bytes:
    """Build one deterministic HTTP response with a stable header order."""
    encoded = body.encode()
    ordered: dict[str, str] = {"Content-Type": "text/html", **dict(headers or {})}
    ordered["Content-Length"] = str(len(encoded))
    head = f"{version} {status}\r\n" + "".join(
        f"{key}: {value}\r\n" for key, value in ordered.items()
    )
    return head.encode() + b"\r\n" + encoded


def _merge_headers(
    canonical: Mapping[str, str] | None, mutation: Mapping[str, str | None] | None
) -> dict[str, str]:
    merged = dict(canonical or {})
    for key, value in dict(mutation or {}).items():
        if value is None:
            merged.pop(key, None)
        else:
            merged[key] = value
    return merged


def render_payload(
    suite_type: str,
    direction: str,
    canonical: Mapping[str, object],
    mutation: Mapping[str, object],
) -> bytes:
    """Apply one case mutation to a canonical payload specification."""
    raw = mutation.get("raw_payload")
    if raw is not None:
        if not isinstance(raw, bytes):
            raise TypeError("raw_payload must be bytes")
        return raw
    spec: dict[str, object] = {
        **dict(canonical),
        **{key: value for key, value in mutation.items() if key not in _TRANSPORT_KEYS},
    }
    if "headers" in mutation:
        spec["headers"] = _merge_headers(
            canonical.get("headers"),  # type: ignore[arg-type]
            mutation["headers"],  # type: ignore[arg-type]
        )
    if suite_type == "raw_tcp":
        payload = spec["payload"]
        if not isinstance(payload, bytes):
            raise TypeError("raw_tcp payload must be bytes")
        return payload
    if suite_type != "http":
        raise ValueError(f"unsupported suite type: {suite_type}")
    headers = spec.get("headers") or {}
    if direction == "to_client":
        return http_response(
            str(spec.get("body", "")),
            status=str(spec.get("status", "200 OK")),
            headers=headers,  # type: ignore[arg-type]
        )
    return http_request(
        str(spec["method"]),
        str(spec["target"]),
        headers=headers,  # type: ignore[arg-type]
        body=str(spec.get("body", "")),
        version=str(spec.get("version", "HTTP/1.1")),
    )


def segment_sizes_for(
    payload: bytes,
    *,
    segment_sizes: tuple[int, ...] | None = None,
    split_after: tuple[bytes, ...] | None = None,
    uniform_segment_size: int | None = None,
) -> tuple[int, ...] | None:
    """Resolve explicit, marker-derived, or uniform TCP segment boundaries."""
    if segment_sizes is not None:
        if sum(segment_sizes) != len(payload):
            raise ValueError("segment_sizes must sum to the payload length")
        return segment_sizes
    if split_after is not None:
        boundaries: list[int] = []
        search = 0
        for marker in split_after:
            found = payload.find(marker, search)
            if found < 0:
                raise ValueError(f"split marker {marker!r} is absent from the payload")
            boundary = found + len(marker)
            search = boundary
            if 0 < boundary < len(payload) and boundary not in boundaries:
                boundaries.append(boundary)
        if not boundaries:
            return None
        sizes: list[int] = []
        previous = 0
        for boundary in boundaries:
            sizes.append(boundary - previous)
            previous = boundary
        if previous < len(payload):
            sizes.append(len(payload) - previous)
        return tuple(sizes)
    if uniform_segment_size is not None:
        if uniform_segment_size <= 0:
            raise ValueError("uniform_segment_size must be positive")
        sizes = [
            min(uniform_segment_size, len(payload) - offset)
            for offset in range(0, len(payload), uniform_segment_size)
        ]
        return tuple(sizes) or None
    return None


def _chunks(payload: bytes, segment_sizes: tuple[int, ...] | None) -> list[bytes]:
    if segment_sizes is None:
        return [payload]
    if sum(segment_sizes) != len(payload):
        raise ValueError("segment_sizes must sum to the payload length")
    chunks: list[bytes] = []
    offset = 0
    for size in segment_sizes:
        chunks.append(payload[offset : offset + size])
        offset += size
    return chunks


def build_established_tcp_stream(
    payload: bytes,
    *,
    port: int,
    direction: str,
    segment_sizes: tuple[int, ...] | None,
    retransmit_segment: int | None,
    established: bool = True,
    preamble: bytes | None = None,
    client_ip: str = CLIENT_IP,
    server_ip: str = SERVER_IP,
) -> list:
    """Build one deterministic TCP conversation carrying the payload."""
    if direction not in {"to_server", "to_client"}:
        raise ValueError(f"unsupported direction: {direction}")

    def to_server(flags: str, seq: int, ack: int, data: bytes | None = None):
        packet = IP(src=client_ip, dst=server_ip) / TCP(
            sport=CLIENT_PORT, dport=port, flags=flags, seq=seq, ack=ack
        )
        return packet / Raw(data) if data is not None else packet

    def to_client(flags: str, seq: int, ack: int, data: bytes | None = None):
        packet = IP(src=server_ip, dst=client_ip) / TCP(
            sport=port, dport=CLIENT_PORT, flags=flags, seq=seq, ack=ack
        )
        return packet / Raw(data) if data is not None else packet

    client_seq = CLIENT_ISN + 1
    server_seq = SERVER_ISN + 1
    if not established:
        packets = [to_server("S", CLIENT_ISN, 0)]
        send = to_server if direction == "to_server" else to_client
        seq = client_seq if direction == "to_server" else server_seq
        for chunk in _chunks(payload, segment_sizes):
            packets.append(send("PA", seq, 0, chunk))
            seq += len(chunk)
        return _with_fixed_timestamps(packets)

    packets = [
        to_server("S", CLIENT_ISN, 0),
        to_client("SA", SERVER_ISN, client_seq),
        to_server("A", client_seq, server_seq),
    ]
    if preamble:
        if direction == "to_server":
            packets.append(to_client("PA", server_seq, client_seq, preamble))
            server_seq += len(preamble)
            packets.append(to_server("A", client_seq, server_seq))
        else:
            packets.append(to_server("PA", client_seq, server_seq, preamble))
            client_seq += len(preamble)
            packets.append(to_client("A", server_seq, client_seq))

    send, acknowledge = (
        (to_server, to_client) if direction == "to_server" else (to_client, to_server)
    )
    sender_seq, receiver_seq = (
        (client_seq, server_seq)
        if direction == "to_server"
        else (server_seq, client_seq)
    )
    for index, chunk in enumerate(_chunks(payload, segment_sizes)):
        data_packet = send("PA", sender_seq, receiver_seq, chunk)
        packets.append(data_packet)
        if retransmit_segment == index:
            packets.append(data_packet.copy())
        sender_seq += len(chunk)
    packets.extend(
        [
            acknowledge("A", receiver_seq, sender_seq),
            send("FA", sender_seq, receiver_seq),
            acknowledge("FA", receiver_seq, sender_seq + 1),
            send("A", sender_seq + 1, receiver_seq + 1),
        ]
    )
    return _with_fixed_timestamps(packets)


def _with_fixed_timestamps(packets: list) -> list:
    for index, packet in enumerate(packets):
        packet.time = BASE_TIMESTAMP + index * 0.001
    return packets


def write_case_pcap(packets: list, output_path: Path) -> Path:
    """Persist one suite case as a deterministic PCAP file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wrpcap(str(output_path), packets)
    return output_path
